### PR TITLE
Display company name (if set) on a Call screen when queueing starts

### PR DESCRIPTION
**Pull request by andrews-moc**
**Jira issue:**
[MOB-3807](https://glia.atlassian.net/browse/MOB-3807)

**What was solved?**
- Display company name (if set) on a Call screen when queueing starts
- Display operator name on a Call screen when operator picks a call

**Release notes:**

 - [ ] Feature
 - [ ] Ignore
 - [x] Release notes (Is it clear from the description here?)
 - [ ] Migration guide (If changes are needed for integrator already using the SDK - what needs to be communicated? Add underneath please)

**Additional info:**

 - [x] Is the feature sufficiently tested? All tests fixed? Necessary unit, acceptance, snapshots added? Check that at least new public classes & methods are covered with unit tests
 - [ ] Did you add logging beneficial for troubleshooting of customer issues?
 - [ ] **Did you add new logging?** We would like the logging between platforms to be similar. Refer to [**Logging from Android SDKs** → **Things to consider for newly added logs**](https://glia.atlassian.net/wiki/spaces/ENG/pages/3568861468/Logging+from+Android+SDKs#Things-to-consider-for-newly-added-logs) in Confluence for more information.

**Screenshots:**

https://github.com/user-attachments/assets/016ed3b9-f5ab-4feb-b414-182aee8a93c6

[MOB-3807]: https://glia.atlassian.net/browse/MOB-3807?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by DavDo — APPROVED** [review]
LGTM

**Comment by andrews-moc** [comment]
@DavDo Thank you for a fast review.
I have updated screenshots for tests. The changes make sense to me (a company name was changed to an operator name for the cases when an operator is connected to the call).

Could you please have a look at the new screenshots as well?

**Review by DavDo — APPROVED** [review]

**Review by gugalo — APPROVED** [review]

**Review by AndriiHorishniiMOC — APPROVED** [review]
Looks good. But where does the "Screenshot Operator" string come on Snapshot tests?

**Comment by andrews-moc** [comment]
> Looks good. But where does the "Screenshot Operator" string come on Snapshot tests?

@AndriiHorishniiMOC The "Screenshot Operator" string is set in snapshot tests as the name of a connected operator.

**Pull request merged**
