### PR TITLE
Add confirmation screen to Secure Messaging

### PR DESCRIPTION
**Pull request by DavDo**
MOB-1729

**Jira issue:**
https://glia.atlassian.net/browse/MOB-1729

**Screenshots:**

https://user-images.githubusercontent.com/19994238/211342123-d81f5be3-21e1-4693-827e-ee224791a7f5.mp4

### CODE REVIEW

**Review by AndriiHorishniiMOC — CHANGES_REQUESTED** [review]
I don't have any questions about the new view. But your changes broke the keyboard behavior on Welcome Screen.

**Comment by DavDo** [comment]
I thout that it can happen, but I compared before and after, and no differences found. Can you please explain what exactly I broke?

**Comment by DavDo** [comment]
I thout that it can happen, but I compared before and after, and no differences found. Can you please explain what exactly I broke?

**Comment by DavDo** [comment]
Got It! Input Must not change the size

**Comment by DavDo** [comment]
@AndriiHorishniiMOC fixed
https://user-images.githubusercontent.com/19994238/211598349-62c5de9f-fda1-47f5-8a31-2be3be0b6fa7.mp4

**Review by AndriiHorishniiMOC — APPROVED** [review]

**Review by gugalo — APPROVED** [review]

**Comment by DavDo** [comment]
!squash

**Comment by DavDo** [comment]
!merge

**Pull request merged**
