### PR TITLE
Open the chat transcript screen by clicking on push notification

### PR DESCRIPTION
**Pull request by AndriiHorishniiMOC**
Open the chat transcript screen by clicking on push notification

MOB-1749

### CODE REVIEW

**Review by Pelkar — COMMENTED** [review]
Do I understand correctly that the integrator must handle the push notification on their own? Does it not make sense to handle it ourselves?

**Review by DavDo — APPROVED** [review]

**Comment by AndriiHorishniiMOC** [comment]
@Pelkar Yes, they should handle it on their own. But if you have an idea how we can handle it inside the SDK we can make a meeting and discuss it.

**Review by Pelkar — APPROVED** [review]

**Comment by Pelkar** [comment]
> @Pelkar Yes, they should handle it on their own. But if you have an idea how we can handle it inside the SDK we can make a meeting and discuss it.

Thank you for the clarification

**Review by andrews-moc — APPROVED** [review]
I don't have any comments.

**Comment by AndriiHorishniiMOC** [comment]
!merge

**Pull request merged**
