### PR TITLE
Gallery card recycler view

### PR DESCRIPTION
**Pull request by AndriiHorishniiMOC**
Created the Gallery list.

RecycleView was configured according to the design.
The RecyclerView scrolling was optimized by pre-calculating the gallery card item height.

[MOB-2408](https://glia.atlassian.net/browse/MOB-2408)

[MOB-2408]: https://glia.atlassian.net/browse/MOB-2408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by Pelkar — APPROVED** [review]

**Review by DavDo — APPROVED** [review]

**Comment by AndriiHorishniiMOC** [comment]
I did changes for the gallery card height calculation. Please, look again this PR.

**Comment by AndriiHorishniiMOC** [comment]
I did changes for the gallery card height calculation. Please, look again this PR.

**Review by DavDo — APPROVED** [review]
LGTM

**Review by andrews-moc — APPROVED** [review]

**Review by Pelkar — APPROVED** [review]
LGTM

**Pull request merged**
