### PR TITLE
Remove "End screen sharing" dialog

### PR DESCRIPTION
**Pull request by jakob-mc**
**Jira issue:**
https://glia.atlassian.net/browse/MUIC-658

### CODE REVIEW

**Review by deniss-mc — APPROVED** [review]

**Review by AndriiHorishniiMOC — APPROVED** [review]

**Review by dukhovnyi — CHANGES_REQUESTED** [review]
I'd like to propose removing the ticket number from the commit title and moving it to the commit description. This change will make git history and changelog more consistent and more readable.

**Comment by jakob-mc** [comment]
> I'd like to propose removing the ticket number from the commit title and moving it to the commit description. This change will make git history and changelog more consistent and more readable.

@dukhovnyi shall we avoid ticket names in commit messages as well?

**Comment by dukhovnyi** [comment]
@jakob-mc yep, I wrote about commit title and commit description, so could you also update commit message?

**Comment by jakob-mc** [comment]
> @jakob-mc yep, I wrote about commit title and commit description, so could you also update commit message?

I misread, will fix it!

**Comment by jakob-mc** [comment]
> @jakob-mc yep, I wrote about commit title and commit description, so could you also update commit message?

@dukhovnyi changed the commit message and description, how does it look?

**Pull request merged**
