### PR TITLE
Confirmation screen in landscape is clipped

### PR DESCRIPTION
**Pull request by DavDo**
MOB 2140

### CODE REVIEW

**Review by AndriiHorishniiMOC — COMMENTED** [review]
The layout is good. But if you change the orientation on the confirmation screen it resets the state.

https://user-images.githubusercontent.com/79906470/235694920-4be1636f-7a48-4dd5-bf74-565ebd71899a.mp4

**Comment by DavDo** [comment]
> The layout is good. But if you change the orientation on the confirmation screen it resets the state.
> 
>  device-2023-05-02-171915.mp4

My bad! I somehow missed this when I was implementing the confirmation screen.

**Comment by DavDo** [comment]
It seems the only way is to save the view state, which is a bit strange in 2023))

**Review by andrews-moc — APPROVED** [review]

**Comment by DavDo** [comment]
!merge

**Pull request merged**
