### PR TITLE
Extend direct id authorization with external_access_token

### PR DESCRIPTION
**Pull request by andrews-moc**
[Integrators want to pass "external_access_token" during DirectID authorization](https://glia.atlassian.net/browse/MOB-2233)

This PR depends on [Core SDK PR](https://github.com/salemove/android-sdk/pull/470)

Screenshot 2023-05-30 at 17 25 20

### CODE REVIEW

**Review by DavDo — APPROVED** [review]
LGTM

**Review by Pelkar — APPROVED** [review]
LGTM

**Comment by gugalo** [comment]
!squash

**Comment by gugalo** [comment]
!merge

**Pull request merged**
