### PR TITLE
Fix typo in custom locale key

### PR DESCRIPTION
**Pull request by gugalo**
**Jira issue:**
https://glia.atlassian.net/browse/MOB-3325

**What was solved?**
I have updated custom locale keys in SDK side to match what is defined for same messages in the remote repository strings:  https://github.com/salemove/mobile-locale/blob/9c84a124018c8b421a8f27e6d6d0267d7ecbf028/locales/en-US.json

**Release notes:**

 - [x] Feature: fixed correct loading of translations from GliaHub for specific string
 - [ ] Ignore
 - [ ] Release notes (Is it clear from the description here?)
 - [ ] Migration guide (If changes are needed for integrator already using the SDK - what needs to be communicated? Add underneath please)

**Additional info:**

 - [ ] Is the feature sufficiently tested? All tests fixed? Necessary unit, acceptance, snapshots added? Check that at least new public classes & methods are covered with unit tests
 - [ ] Did you add logging beneficial for troubleshooting of customer issues?
 - [ ] **Did you add new logging?** We would like the logging between platforms to be similar. Refer to [**Logging from Android SDKs** → **Things to consider for newly added logs**](https://glia.atlassian.net/wiki/spaces/ENG/pages/3568861468/Logging+from+Android+SDKs#Things-to-consider-for-newly-added-logs) in Confluence for more information.

**Screenshots:**

### CODE REVIEW

**Review by DavDo — APPROVED** [review]

**Review by AndriiHorishniiMOC — APPROVED** [review]

**Comment by andrews-moc** [comment]
@gugalo You have specified that these changes are related to **_How can we reduce Android (warning) logs?_** ticket. Just for better understanding, how are these changes connected with logging?

**Review by andrews-moc — APPROVED** [review]

**Comment by andrews-moc** [comment]
> @gugalo You have specified that these changes are related to **_How can we reduce Android (warning) logs?_** ticket. Just for better understanding, how are these changes connected with logging?

I figured out - it's related to the error logs coming from acceptance tests, I suppose.

**Comment by gugalo** [comment]
@andrews-moc Yes, you are right. We had warning logs coming from both the acceptance and production environment. Something like: 
`Key does not exists in remote strings $key_name`

**Comment by gugalo** [comment]
!squash

**Pull request merged**
