### PR TITLE
Fix screen sharing dialog not shown bug

### PR DESCRIPTION
**Pull request by jakob-mc**
**Jira issue:**
https://glia.atlassian.net/browse/MUIC-457

### CODE REVIEW

**Review by deniss-mc — CHANGES_REQUESTED** [review]
Returns bug when CallView is on top of ChatView - onResume is called

**Comment by jakob-mc** [comment]
> Returns bug when CallView is on top of ChatView - onResume is called when orientation is changed

how does the bug manifest itself?

**Comment by jakob-mc** [comment]
> Returns bug when CallView is on top of ChatView - onResume is called when orientation is changed

I reverted the isFinishing boolean logic only for ChatHead controller since other controllers seem to work well. I also made dialog controller lifecycle-aware. Now, if the view is paused, it does not try to display any dialogs.

**Review by dukhovnyi — CHANGES_REQUESTED** [review]
I'd like to propose removing the ticket number from the commit title and moving it to the commit description. This change will make git history and changelog more consistent and more readable.

**Comment by jakob-mc** [comment]
> I'd like to propose removing the ticket number from the commit title and moving it to the commit description. This change will make git history and changelog more consistent and more readable.

done

**Comment by dukhovnyi** [comment]
looks like you have changed the PR name, but not commit message. or do I miss something?

**Review by andrews-moc — APPROVED** [review]

**Review by dukhovnyi — APPROVED** [review]

**Review by deniss-mc — APPROVED** [review]

**Pull request merged**
