### PR TITLE
Upgrade compile, target and AGP versions

### PR DESCRIPTION
**Pull request by DavDo**
**Jira issue:**
https://glia.atlassian.net/browse/MOB-3551

**What was solved?**
- Upgrade Widgets SDK Compile SDK version to 34
- Upgrade Testing app Compile and target SDK versions to 35
- Upgrade the AGP version to the latest version(8.6)
- Upgrade third-party dependencies
- Upgrade the Core SDK dependency version to 1.8.0

**Release notes:**
- Android 15(Target SDK 35) support.
- Upgrade the minimum supported compileSDK to 34

 - [ ] Feature
 - [ ] Ignore
 - [x] Release notes (Is it clear from the description here?)
 - [ ] Migration guide (If changes are needed for integrator already using the SDK - what needs to be communicated? Add underneath please)

**Additional info:**

 - [ ] Is the feature sufficiently tested? All tests fixed? Necessary unit, acceptance, snapshots added? Check that at least new public classes & methods are covered with unit tests
 - [ ] Did you add logging beneficial for troubleshooting of customer issues?
 - [ ] **Did you add new logging?** We would like the logging between platforms to be similar. Refer to [**Logging from Android SDKs** → **Things to consider for newly added logs**](https://glia.atlassian.net/wiki/spaces/ENG/pages/3568861468/Logging+from+Android+SDKs#Things-to-consider-for-newly-added-logs) in Confluence for more information.

**Screenshots:**

### CODE REVIEW

**Review by EgorovEI — APPROVED** [review]

**Review by gugalo — APPROVED** [review]
Are these changes backword compatible?
Can you publish to locale maven and use them with CortexFinacial without incrementing the gradle version or changing the target SDK to API 35?

**Comment by DavDo** [comment]
> Are these changes backward compatible? Can you publish to locale maven and use this Widget version with CortexFinacial without incrementing the gradle version or changing the target SDK to API 35?

these changes should be backwards compatible, but I will check before merging them.

**Comment by DavDo** [comment]
there are mostly no differences between the old and new snapshots, except the Operator attachment-related cases where the Paparazzi is having some problems with the Formatter so the `KB` somehow gets replaced with the `kilobyteShort` but in runtime, there is no such problem. Also, upgrading Paparazzi to the latest version fixes this, but since it is bumping the Kotlin version to 1.9 for an entire project, we can’t do it now.
image

**Comment by DavDo** [comment]
It seems all the failing snapshots are related to the paparazzi-related changes, so we will probably face the same problems when upgrading the Paparazzi version with Kotlin being 1.9

**Pull request merged**
