### PR TITLE
[Backport] Deprecate Styles

### PR DESCRIPTION
**Pull request by DavDo**
**Jira issue:**
https://glia.atlassian.net/browse/MOB-xxx

**What was solved?**

**Release notes:**

 - [ ] Feature
 - [x] Ignore
 - [ ] Release notes (Is it clear from the description here?)
 - [ ] Migration guide (If changes are needed for integrator already using the SDK - what needs to be communicated? Add underneath please)

**Additional info:**

 - [ ] Tests updated? Added? Unit, acceptance, snapshots?
 - [ ] Logging for future troubleshooting of client issues added?

**Screenshots:**

### CODE REVIEW

**Review by Pelkar — APPROVED** [review]
LGTM. However I am a little concerned that we are deprecating all finer customisation. This will still be available to those who want to use those, but still. We might want to go over all the finer styling types and make sure we want to not have this from this point onward

**Review by andrews-moc — COMMENTED** [review]
To double check, you are not just deprecating but removing right away? I was under impression that we agreed to mark as deprecated and remove from the docs.

**Comment by DavDo** [comment]
Regarding deprecation, I think that's the only way atm because these styles are working partially(applying everything except colors), so yes, we must investigate if we need them at all or not.

**Comment by DavDo** [comment]
> To double check, you are not just deprecating but removing right away? I was under impression that we agreed to mark as deprecated and remove from the docs.

No, we're just deprecating, I removed examples from the example app.

**Review by andrews-moc — APPROVED** [review]

**Comment by andrews-moc** [comment]
> No, we're just deprecating, I removed examples from the example app.

Ah, got it, thanks.

**Pull request merged**
