### PR TITLE
Add custom API docs lint checker

### PR DESCRIPTION
**Pull request by gugalo**
**Jira issue:**
https://glia.atlassian.net/browse/MOB-3172

**What was solved?**
Have created a lint checker that will detect any public classes that have no in-code documentation

**Release notes:**

 - [ ] Feature
 - [x] Ignore. This change is for internal use
 - [ ] Release notes (Is it clear from the description here?)
 - [ ] Migration guide (If changes are needed for integrator already using the SDK - what needs to be communicated? Add underneath please)

**Additional info:**

 - [x] Tests updated? Added? Unit, acceptance, snapshots?
 - [ ] Logging for future troubleshooting of client issues added?

**Screenshots:**

It might not show in the editor right away needs to have the project built or re-build first.
image

When a lint report is generated
image

image

### CODE REVIEW

**Review by Pelkar — APPROVED** [review]
LGTM

Just to confirm, this lint check is being run. every build?

**Comment by gugalo** [comment]
It is a bit more complicated than a simple yes or no.
This lint check will not affect normal builds. But ideally, it should highlight this error in code in AndroidStudio. See screenshots in the PR description and also [this part](https://github.com/salemove/android-sdk-widgets/blob/b11ff5a63a31eb1890d95ed2b65b2dce4ab6bdd1/lint_checker/src/main/java/com/glia/widgets/lint/UndocumentedApiDetector.kt#L40) could be relevant to your question

**Review by DavDo — APPROVED** [review]

**Comment by gugalo** [comment]
Found a problem with the detection of Kotlin in code docs. Made a small fix. Please review these changes to the PR: https://github.com/salemove/android-sdk-widgets/pull/976/commits/4a6481f4a5682a21b77b634bff748d60d9343a0f

**Review by DavDo — APPROVED** [review]

**Review by andrews-moc — APPROVED** [review]
Thank you for adding comments 👍

**Review by Pelkar — APPROVED** [review]
LGTM

**Review by AndriiHorishniiMOC — APPROVED** [review]
Good job!

**Pull request merged**
