### PR TITLE
Add correct commit author to Bitrise commits

### PR DESCRIPTION
**Pull request by gersonnoboa**
Bitrise does commits sometimes for us, like for example updating dependencies. Bitrise's documentation recommends to introduce an envvar with the values. These are the same values used in other projects.

MOB-1696

### CODE REVIEW

**Comment by gersonnoboa** [comment]
https://github.com/salemove/android-sdk-widgets/pull/629/files#diff-61d1ee831cb1df242161a7d23171914a1d5d628c7659b52db957d80a9394bd68R423

**Review by DavDo — APPROVED** [review]

**Comment by andrews-moc** [comment]
@gersonnoboa Let me clarify, if I see the actual changes right - `GIT_AUTHOR_NAME` and `GIT_AUTHOR_EMAIL` were added. All the rest is reformatting, right?

**Review by andrews-moc — COMMENTED** [review]
@gersonnoboa Let me clarify, if I see the actual changes right - GIT_AUTHOR_NAME and GIT_AUTHOR_EMAIL were added. All the rest is reformatting, right?

**Review by gugalo — APPROVED** [review]

**Comment by andrews-moc** [comment]
I think we should either change the target branch to `development` or leave `master` as a target but keep in mind to create backport commit to `development`.

**Comment by gersonnoboa** [comment]
@andrews-moc that should be done as part of another PR, so that we can rollback easily in case something goes wrong.

**Comment by gersonnoboa** [comment]
!merge

**Pull request merged**
