### PR TITLE
Fix CV confirmation dialog absence when returning from WebBrowser

### PR DESCRIPTION
**Pull request by DavDo**
**Jira issue:**
https://glia.atlassian.net/browse/MOB-3140

**What was solved?**

**Release notes:**

 - [ ] Feature
 - [x] Ignore
 - [ ] Release notes (Is it clear from the description here?)
 - [ ] Migration guide (If changes are needed for integrator already using the SDK - what needs to be communicated? Add underneath please)

**Additional info:**

 - [x] Tests updated? Added? Unit, acceptance, snapshots?
 - [ ] Logging for future troubleshooting of client issues added?

**Screenshots:**

### CODE REVIEW

**Review by andrews-moc — COMMENTED** [review]
Could you please provide the steps to reproduce? Also, ticket link opens 3138 instead of 3140.

**Comment by DavDo** [comment]
> Could you please provide the steps to reproduce? Also, ticket link opens 3138 instead of 3140.

Sure. I'd like to remind you that this is happening on the refactoring branch only.

1. Open visitor code dialog
2. input code from the operator side and request CV
3. When the Confirmation dialog is opened click on link1 or link2
4. Link should be opened inside WebBrowserActivity
5. Return from the WebBrowser activity

**Expected Result:**
Confirmation dialog should be re-displayed

**Actual Result:**
Nothing Happens

**Review by andrews-moc — APPROVED** [review]

**Comment by Pelkar** [comment]
I have an issue with this. 

I would argue that the correct implementation is to close the dialog, because the timeout on the backend side happens at 15 seconds.

Ofc the best UX would be to display a new dialog, that explains that the attempt has timed out and we need to try again.

The current implementation kind-of connects and visitor is not informed that the connection has failed

**Comment by DavDo** [comment]
> I have an issue with this.
> 
> I would argue that the correct implementation is to close the dialog, because the timeout on the backend side happens at 15 seconds.
> 
> Ofc the best UX would be to display a new dialog, that explains that the attempt has timed out and we need to try again.
> 
> The current implementation kind-of connects and visitor is not informed that the connection has failed

These changes were made to align the behavior after refactoring with the current one. I like your suggestion, but I think it should be discussed separately and implemented as a separate improvement.

**Review by Pelkar — APPROVED** [review]

**Pull request merged**
