### PR TITLE
Call Visualizer acceptance tests

### PR DESCRIPTION
**Pull request by gugalo**
**Jira issue:**
https://glia.atlassian.net/browse/MOB-1820

Did tiny improvements related to acceptance tests

### CODE REVIEW

**Review by Pelkar — APPROVED** [review]
LGTM 👍

**Review by andrews-moc — APPROVED** [review]

**Review by DavDo — APPROVED** [review]

**Comment by gugalo** [comment]
I don't get how my changes have affected a Unit test `ActivityWatcherControllerTest` ;/

**Comment by DavDo** [comment]
> Details

Maybe Need to add `GrantPermissionRule`?

**Comment by DavDo** [comment]
> Maybe Need to add `GrantPermissionRule`?

Maybe Need to add GrantPermissionRule?

**Comment by DavDo** [comment]
> I don't get how my changes have affected a Unit test `ActivityWatcherControllerTest` ;/ And worse is that I have rerun Bitrise 3 times and it failed every time with same error

Maybe Need to add `GrantPermissionRule?

**Comment by gugalo** [comment]
!merge

**Pull request merged**
