### PR TITLE
Added service cleanup on app destroy

### PR DESCRIPTION
**Pull request by Pelkar**
MOB-2034

Added service cleanup on app destroy

### CODE REVIEW

**Comment by andrews-moc** [comment]
@Pelkar I'm a little confused.

The issue is: "Screen notification is shown before system permission is shown and thus shown even if permission is declined". So I expect something wrong in the sequence - notification should probably be shown after permission is granted. 

PR description mentions app destroy, however, my understanding is that the issue is reproduced regardless of the app closing.

Could you please shed light on my confusion - how is app destroy connected with rejecting permission?

**Comment by Pelkar** [comment]
> @Pelkar I'm a little confused.
> 
> The issue is: "Screen notification is shown before system permission is shown and thus shown even if permission is declined". So I expect something wrong in the sequence - notification should probably be shown after permission is granted.
> 
> PR description mentions app destroy, however, my understanding is that the issue is reproduced regardless of the app closing.
> 
> Could you please shed light on my confusion - how is app destroy connected with rejecting permission?

Me too, you seem to be quoting another ticket:
image

**Comment by andrews-moc** [comment]
@Pelkar Oh, sorry, indeed.

**Review by andrews-moc — APPROVED** [review]

**Review by gugalo — APPROVED** [review]

**Review by DavDo — COMMENTED** [review]
LGTM

**Pull request merged**
