### PR TITLE
- Handle Broadcast events

### PR DESCRIPTION
**Pull request by DavDo**
**Jira issue:**
https://glia.atlassian.net/browse/MOB-2389

Show Toast message — “This action is not currently supported on mobile'.

### CODE REVIEW

**Review by AndriiHorishniiMOC — APPROVED** [review]
LGTM

**Comment by EgorovEI** [comment]
Project plan says:
On the GVA side, there is a feature flag to show/hide this type of button, and it is and should always be off. So this kind of buttons shouldn’t appear on mobile GVA. But to make sure that in case if they sneak into a mobile GVA, will not break the SDK, it should be rendered, but will **show an error message to the user (“This feature is not supported on mobile”) and log an error (level = info) when clicked.**

I guess you also need to add logging.

**Review by gugalo — COMMENTED** [review]
No notes from me, but Egor mentioned some missing logging

**Comment by DavDo** [comment]
> Project plan says: On the GVA side, there is a feature flag to show/hide this type of button, and it is and should always be off. So this kind of buttons shouldn’t appear on mobile GVA. But to make sure that in case if they sneak into a mobile GVA, will not break the SDK, it should be rendered, but will **show an error message to the user (“This feature is not supported on mobile”) and log an error (level = info) when clicked.**
> 
> I guess you also need to add logging.

Good point. I will remove the logging part from the project plan. 
When we started working on the project, there was an idea to just silently log the error when this type of button is clicked. 
But with Aksel, we figured out that this could confuse visitors, so we decided to replace the log with a toast message. I think there is no benefit to logging.

**Comment by DavDo** [comment]
!squash

**Pull request merged**
