### PR TITLE
Incremented Core version and cleanup of base resources

### PR DESCRIPTION
**Pull request by Pelkar**
Incremented Core version, resource cleanup for Custom Locales release

**Release notes:**

 - [x] Feature
 - [ ] Ignore
 - [ ] Release notes (Is it clear from the description here?)
 - [ ] Migration guide (If changes are needed for integrator already using the SDK - what needs to be communicated? Add underneath please)

### CODE REVIEW

**Review by andrews-moc — APPROVED** [review]
Do you want me to close the [Increment Core SDK version to 1.1.5](https://github.com/salemove/android-sdk-widgets/pull/800) PR?

**Comment by andrews-moc** [comment]
I checked Bitrise, looks like a temporary failure. Triggered rebuild just now.

**Review by DavDo — APPROVED** [review]
LGTM

**Review by gugalo — APPROVED** [review]
Not sure what to check here

**Review by AndriiHorishniiMOC — APPROVED** [review]

**Pull request closed without merging**
